// This file was auto-generated by ML.NET Model Builder. 
using JFP.Server.Extensions;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi.Models;

// Configure app
var builder = WebApplication.CreateBuilder(args);

// Configure Services
builder.Services.AddPredictionModels();
builder.Services.AddPredictionServices();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Joensuu Feedback API", Description = "API for the Joensuu Feedback Platform", Version = "v1" });
});

builder.Services.AddControllersWithViews();

var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});

app.UseStaticFiles();
app.MapControllers();

// Run app
app.Run();
